# Generated by Django 2.2.3 on 2019-07-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_customerevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='default_billing_address',
            new_name='tak_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='default_shipping_address',
        ),
    ]
