# Generated by Django 2.2.3 on 2019-07-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20190709_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='tak_address',
            new_name='default_address',
        ),
    ]
